Workapce : 
Workspace_name : "Exam_prep"
Workspace_location :  "eastus"
Workspace_display_name : "Exam_prep_workspace"
Workspace_description :  "this example shows how to create a workspace for azure ml"